apiVersion: apps/v1
kind: Deployment

metadata:
  name: ci-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ci-app

  template:
    metadata:
      labels:
        app: ci-app

    spec:
      containers:
      - name: ci-app
        image: sheetalrkamble01/ci-python-app:v1

        ports:
        - containerPort: 80
